version: 2.1

orbs:
  android: circleci/android@2.5.0
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  spotless-klint:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          command: |
            sudo chmod +x gradlew
            ./gradlew spotlessCheck

  unit-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew :data-android:testDebug
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/data-android/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  test-and-build:
    jobs:
      - spotless-klint
      - unit-test
