package app.cookery.domain.model

data class MealDetails(
    val mealId: String? = null,
    val mealName: String? = null,
    val mealCategory: String? = null,
    val mealArea: String? = null,
    val cookingInstructions: String? = null,
    val mealImage: String? = null,
    val mealTags: String? = null,
    val mealYoutube: String? = null,
    val mealIngredient1: String? = null,
    val mealIngredient2: String? = null,
    val mealIngredient3: String? = null,
    val mealIngredient4: String? = null,
    val mealIngredient5: String? = null,
    val mealIngredient6: String? = null,
    val mealIngredient7: String? = null,
    val mealIngredient8: String? = null,
    val mealIngredient9: String? = null,
    val mealIngredient10: String? = null,
    val mealIngredient11: String? = null,
    val mealIngredient12: String? = null,
    val mealIngredient13: String? = null,
    val mealIngredient14: String? = null,
    val mealIngredient15: String? = null,
    val mealIngredient16: String? = null,
    val mealIngredient17: String? = null,
    val mealIngredient18: String? = null,
    val mealIngredient19: String? = null,
    val mealIngredient20: String? = null,
    val mealMeasure1: String? = null,
    val mealMeasure2: String? = null,
    val mealMeasure3: String? = null,
    val mealMeasure4: String? = null,
    val mealMeasure5: String? = null,
    val mealMeasure6: String? = null,
    val mealMeasure7: String? = null,
    val mealMeasure8: String? = null,
    val mealMeasure9: String? = null,
    val mealMeasure10: String? = null,
    val mealMeasure11: String? = null,
    val mealMeasure12: String? = null,
    val mealMeasure13: String? = null,
    val mealMeasure14: String? = null,
    val mealMeasure15: String? = null,
    val mealMeasure16: String? = null,
    val mealMeasure17: String? = null,
    val mealMeasure18: String? = null,
    val mealMeasure19: String? = null,
    val mealMeasure20: String? = null,
) {
    fun getIngredientsList() = listOf(
        Ingredient(mealMeasure1, mealIngredient1),
        Ingredient(mealMeasure2, mealIngredient2),
        Ingredient(mealMeasure3, mealIngredient3),
        Ingredient(mealMeasure4, mealIngredient4),
        Ingredient(mealMeasure5, mealIngredient5),
        Ingredient(mealMeasure6, mealIngredient6),
        Ingredient(mealMeasure7, mealIngredient7),
        Ingredient(mealMeasure8, mealIngredient8),
        Ingredient(mealMeasure9, mealIngredient9),
        Ingredient(mealMeasure10, mealIngredient10),
        Ingredient(mealMeasure11, mealIngredient11),
        Ingredient(mealMeasure12, mealIngredient12),
        Ingredient(mealMeasure13, mealIngredient13),
        Ingredient(mealMeasure14, mealIngredient14),
        Ingredient(mealMeasure15, mealIngredient15),
        Ingredient(mealMeasure16, mealIngredient16),
        Ingredient(mealMeasure17, mealIngredient17),
        Ingredient(mealMeasure18, mealIngredient18),
        Ingredient(mealMeasure19, mealIngredient19),
        Ingredient(mealMeasure20, mealIngredient20)
    )
}

data class Ingredient(
    val measure: String?,
    val ingredient: String?
)
